# Example awsideman configuration with profile-specific cache settings
# This file should be placed at ~/.awsideman/config.yaml

# Default profile to use when none is specified
default_profile: floccus

# Global cache configuration (used as fallback for profiles without specific config)
cache:
  enabled: true
  default_ttl: 3600  # 1 hour
  max_size_mb: 100
  backend_type: file  # Default backend type

  # Profile-specific cache configurations
  profiles:
    # Production profile with DynamoDB backend
    prod:
      backend_type: dynamodb
      dynamodb_table_name: awsideman-cache-prod
      dynamodb_region: eu-north-1
      dynamodb_profile: prod  # Use prod profile for DynamoDB access
      encryption_enabled: true
      encryption_type: aes256
      default_ttl: 7200  # 2 hours for production
      max_size_mb: 500   # Larger cache for production

    # Development profile with file backend
    dev:
      backend_type: file
      file_cache_dir: ~/.awsideman/cache/dev
      default_ttl: 1800  # 30 minutes for development
      max_size_mb: 50    # Smaller cache for development
      encryption_enabled: false

    # Staging profile with hybrid backend
    staging:
      backend_type: hybrid
      dynamodb_table_name: awsideman-cache-staging
      dynamodb_region: eu-north-1
      dynamodb_profile: staging
      file_cache_dir: ~/.awsideman/cache/staging
      hybrid_local_ttl: 600  # 10 minutes local cache
      encryption_enabled: true
      encryption_type: aes256
      default_ttl: 3600
      max_size_mb: 200

    # Floccus profile (default) with DynamoDB backend
    floccus:
      backend_type: dynamodb
      dynamodb_table_name: awsideman-cache-floccus
      dynamodb_region: eu-north-1
      # dynamodb_profile not specified - will use the same profile (floccus)
      encryption_enabled: false  # No encryption for local development
      default_ttl: 3600
      max_size_mb: 100

# Other configuration sections remain the same
rollback:
  enabled: true
  retention_days: 90
  auto_cleanup: true

templates:
  storage_directory: ~/.awsideman/templates
  default_format: yaml

backup:
  storage:
    default_backend: filesystem
    filesystem:
      path: ~/.awsideman/backups
