# Example awsideman configuration file
# Save this as ~/.awsideman/config.yaml

# Default profile to use when none is specified
default_profile: "production"

# AWS profiles configuration
profiles:
  production:
    region: "us-east-1"
    sso_instance_arn: "arn:aws:sso:::instance/ssoins-1234567890abcdef"
    sso_display_name: "Production SSO"

  development:
    region: "us-west-2"
    sso_instance_arn: "arn:aws:sso:::instance/ssoins-abcdef1234567890"
    sso_display_name: "Development SSO"

  staging:
    region: "eu-west-1"
    sso_instance_arn: "arn:aws:sso:::instance/ssoins-fedcba0987654321"
    sso_display_name: "Staging SSO"

# Cache configuration
cache:
  # Basic cache settings
  enabled: true
  default_ttl: 3600  # 1 hour in seconds
  max_size_mb: 100

  # Backend configuration
  backend_type: "dynamodb"  # Options: "file", "dynamodb", "hybrid"

  # DynamoDB backend settings (only used if backend_type is "dynamodb" or "hybrid")
  dynamodb_table_name: "awsideman-cache"
  dynamodb_region: "us-east-1"
  dynamodb_profile: "production"  # Optional: AWS profile to use for DynamoDB

  # File backend settings (only used if backend_type is "file" or "hybrid")
  file_cache_dir: "~/.awsideman/cache"  # Optional: custom cache directory

  # Encryption settings
  encryption_enabled: true
  encryption_type: "aes256"  # Options: "none", "aes256"

  # Hybrid backend settings (only used if backend_type is "hybrid")
  hybrid_local_ttl: 300  # 5 minutes local cache for hybrid mode

  # Operation-specific TTL overrides (optional)
  operation_ttls:
    list_users: 3600      # 1 hour
    list_groups: 3600     # 1 hour
    list_permission_sets: 7200  # 2 hours
    describe_user: 1800   # 30 minutes
    describe_group: 1800  # 30 minutes
    describe_permission_set: 1800  # 30 minutes
    list_accounts: 7200   # 2 hours
    describe_account: 3600  # 1 hour
    list_account_assignments: 1800  # 30 minutes

# Rollback configuration
rollback:
  # Basic rollback settings
  enabled: true
  storage_directory: "~/.awsideman/operations"
  retention_days: 90
  auto_cleanup: true
  max_operations: 10000
  confirmation_required: true
  dry_run_default: false

  # Verification settings for handling AWS Identity Center eventual consistency
  verification:
    enabled: true                    # Whether to perform post-rollback verification
    delay_seconds: 10               # Wait time before verification (allows IdC to propagate changes)
    max_retries: 3                  # Maximum verification attempts
    retry_delay_seconds: 5          # Initial delay between retries (exponential backoff)

# Backup configuration
backup:
  # Storage configuration
  storage:
    default_backend: "filesystem"    # Options: "filesystem", "s3"
    filesystem:
      path: "~/.awsideman/backups"  # Local backup directory
    s3:
      bucket: null                   # S3 bucket name (must be configured)
      prefix: "backups"              # S3 key prefix
      region: null                   # S3 region (uses profile region if not specified)

  # Encryption settings
  encryption:
    enabled: true                    # Enable backup encryption
    type: "aes256"                  # Encryption type: "none", "aes256"

  # Compression settings
  compression:
    enabled: true                    # Enable backup compression
    type: "gzip"                    # Compression type: "none", "gzip"

  # Default backup settings
  defaults:
    backup_type: "full"             # Default backup type: "full", "incremental"
    include_inactive_users: false   # Include inactive users by default
    resource_types: "all"           # Default resources: "all", "users", "groups", "permission_sets", "assignments"

  # Retention policy
  retention:
    keep_daily: 7                   # Keep daily backups for 7 days
    keep_weekly: 4                  # Keep weekly backups for 4 weeks
    keep_monthly: 12                # Keep monthly backups for 12 months
    auto_cleanup: true              # Automatically clean up old backups

  # Performance settings
  performance:
    deduplication_enabled: true     # Enable deduplication to reduce storage
    parallel_processing_enabled: true  # Enable parallel processing
    resource_monitoring_enabled: true  # Enable resource monitoring
    max_workers: 8                  # Maximum number of worker threads
